# Generated by Django 5.2.13 on 2026-04-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("opinions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_score", models.FloatField(default=0.0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("warning_reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "未处理"),
                            ("processing", "处理中"),
                            ("closed", "已关闭"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_warnings",
                        to="analysis.analysisresult",
                    ),
                ),
                (
                    "opinion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_warnings",
                        to="opinions.opiniondata",
                    ),
                ),
            ],
        ),
    ]
