# Generated by Django 5.2.13 on 2026-04-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("risk_warnings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=50)),
                ("action_content", models.TextField()),
                ("effect_description", models.TextField(blank=True, default="")),
                ("operator", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "warning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_records",
                        to="risk_warnings.riskwarning",
                    ),
                ),
            ],
        ),
    ]
