# Generated by Django 5.2.13 on 2026-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlerTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待运行"),
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("total_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
        ),
    ]
