# Generated by Cursor (manual) for v1.3.0.
#
# Note: This migration intentionally rebuilds crawler_tasks models to match v1.3.0.
# Existing MVP CrawlerTask table is dropped (MVP-only historical data).

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crawler_tasks", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CrawlerTask",
        ),
        migrations.CreateModel(
            name="CrawlerSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("source_type", models.CharField(choices=[("rss", "RSS"), ("static", "Static page"), ("dynamic", "Dynamic page"), ("api", "API"), ("search", "Search")], max_length=20)),
                ("base_url", models.URLField()),
                ("adapter_name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("robots_required", models.BooleanField(default=True)),
                ("rate_limit_seconds", models.IntegerField(default=2)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TopicProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("exclude_keywords", models.JSONField(blank=True, default=list)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("risk_words", models.JSONField(blank=True, default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CrawlerTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_name", models.CharField(max_length=200)),
                ("task_type", models.CharField(choices=[("monitor", "监控"), ("search", "搜索")], max_length=20)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("pending", "待运行"), ("running", "运行中"), ("paused", "已暂停"), ("stopped", "已停止"), ("finished", "已完成"), ("failed", "失败")], default="pending", max_length=20)),
                ("schedule_type", models.CharField(choices=[("once", "单次"), ("interval", "间隔"), ("cron", "Cron")], default="once", max_length=20)),
                ("interval_minutes", models.IntegerField(blank=True, null=True)),
                ("max_items_per_run", models.IntegerField(default=20)),
                ("auto_analyze", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sources", models.ManyToManyField(blank=True, related_name="tasks", to="crawler_tasks.crawlersource")),
                ("topic_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="crawler_tasks.topicprofile")),
            ],
        ),
        migrations.CreateModel(
            name="CrawlerRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("running", "运行中"), ("success", "成功"), ("failed", "失败"), ("canceled", "取消")], default="running", max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_fetched", models.IntegerField(default=0)),
                ("total_valid", models.IntegerField(default=0)),
                ("total_inserted", models.IntegerField(default=0)),
                ("total_duplicated", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="crawler_tasks.crawlertask")),
            ],
        ),
        migrations.CreateModel(
            name="CrawledItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.TextField(blank=True, default="")),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                ("source_url", models.URLField(blank=True, default="")),
                ("publish_time", models.DateTimeField(blank=True, null=True)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("content_hash", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("source_url_hash", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("opinion_id", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(choices=[("new", "新建"), ("inserted", "已入库"), ("duplicate", "重复"), ("failed", "失败")], default="new", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="crawler_tasks.crawlerrun")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="crawler_tasks.crawlertask")),
            ],
        ),
    ]

