# Generated by Django 5.2.13 on 2026-05-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler_tasks", "0003_crawlersource_source_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlersource",
            name="source_code",
            field=models.SlugField(
                help_text="稳定业务标识（脚本/集成用）；主键 id 在开发清库后会变。",
                max_length=100,
                unique=True,
            ),
        ),
    ]
