# Generated by Django 5.2.13 on 2026-04-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opinions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rumor_label",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("rumor_probability", models.FloatField(default=0.0)),
                (
                    "sentiment_label",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("sentiment_probability", models.FloatField(default=0.0)),
                ("keywords", models.JSONField(blank=True, default=list)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opinion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="opinions.opiniondata",
                    ),
                ),
            ],
        ),
    ]
