# Generated by Django 5.2.13 on 2026-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpinionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                ("source_url", models.URLField(blank=True, default="")),
                ("publish_time", models.DateTimeField(blank=True, null=True)),
                ("crawl_time", models.DateTimeField(blank=True, null=True)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("raw_label", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "新建"),
                            ("analyzed", "已分析"),
                            ("warned", "已预警"),
                            ("closed", "已关闭"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
