# Generated by Django 5.2.13 on 2026-04-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opinions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opiniondata",
            name="keywords",
            field=models.JSONField(blank=True, default=list, verbose_name="关键词"),
        ),
    ]

